name: flutter_image_compress
description: Compress Pictures. Can effectively reduce the size of the transmission.
repository: https://github.com/fluttercandies/flutter_image_compress
version: 2.0.3

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.7.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_image_compress_platform_interface:
    git:
      url: git@github.com:ibrahimMahfuz/flutter_image_compress.git
      path: packages/flutter_image_compress_platform_interface
      ref: adjust-2.0.0
  flutter_image_compress_common:
    git:
      url: git@github.com:ibrahimMahfuz/flutter_image_compress.git
      path: packages/flutter_image_compress_common
      ref: adjust-2.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_image_compress_common
      ios:
        default_package: flutter_image_compress_common