name: flutter_image_compress_platform_interface
description: The platform interface of flutter_image_compress.
repository: https://github.com/fluttercandies/flutter_image_compress
version: 1.0.1

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.7.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^1.0.3
  cross_file: ^0.2.1